sonar.organization=trbroyles1
sonar.projectKey=trbroyles1_shipyard

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/__tests__/**,src/test/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/__tests__/**,src/test/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/*.d.ts
sonar.css.file.suffixes=.css,.module.css
